services:
  voyager_ai_gw:
    image: voyager_ai_gw:latest
    build:
      context: .
      args:
        target: runtime
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/voyager_ai_gw"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    restart: always
    container_name: voyager_ai_gw_db
    environment:
      POSTGRES_DB: voyager_ai_gw
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d voyager_ai_gw -U gateway_app"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
    name: voyager_ai_gw_postgres_data
