version: "3.9"

services:
  voyager_ai_gw:
    build:
      context: .
      args:
        target: runtime
    image: voyager-ai-gateway:latest
    volumes:
      - ./config.yaml:/app/config.yaml
    command:
      - "--config=/app/config.yaml"
    expose:
      - "4000"
    environment:
      DATABASE_URL: "postgresql://llmproxy:voyager_ai_gw@db:5432/voyager_ai_gw"
      STORE_MODEL_IN_DB: "True"
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 http://localhost:4000/health/liveliness || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    restart: always
    container_name: voyager_ai_gw_db
    environment:
      POSTGRES_DB: voyager_ai_gw
      POSTGRES_USER: llmproxy
      POSTGRES_PASSWORD: voyager_ai_gw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d voyager_ai_gw -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - voyager_ai_gw
    restart: always

volumes:
  postgres_data:
    name: voyager_ai_gw_postgres_data
