name: Deploy to GCP VM

# Trigger workflow only on push to release/prod branch
on:
  workflow_dispatch:
  push:
    branches:
      - release/prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e

            # Navigate to application folder
            mkdir -p ~/gateway
            cd ~/gateway

            # Update code from GitHub
            git fetch --all
            git reset --hard origin/release/prod

            # Write .env from GitHub Secrets
            cat > .env << 'EOT'
            ${{ secrets.ENV_FILE }}
            EOT
            chmod 600 .env

            # Stop current containers safely
            docker compose -f docker-compose.prod.yml down --remove-orphans

            # Prune only unused images to avoid deleting unrelated containers
            docker image prune -af

            # Build and start containers
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d

            # Optional: show running containers for verification
            docker ps
          EOF
